<?php

$trans = [

    'ar' => [
        'dashboard' => 'لوحة التحكم',
        'home' => 'الرئيسية',
        'drivers' => 'السائقين',
        'vehicles' => 'المركبات',
        'expenses' => 'البنزين والصيانة',
        'reports' => 'التقارير',
        'logout' => 'تسجيل خروج',
        'welcome' => 'مرحباً',
        'confirm_logout' => 'تأكيد الخروج',
        'logout_msg' => 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
        'cancel' => 'إلغاء',
        'yes_logout' => 'نعم، تسجيل الخروج',
        'dashboard_title' => 'الرئيسية',
        'choose_month' => 'اختر الشهر',
        'drivers_count' => 'عدد السائقين',
        'vehicles_count' => 'عدد المركبات',
        'fuel_expense' => 'مصروف البنزين',
        'maintenance_expense' => 'مصروف الصيانة',
        'internet_expense' => 'مصروف الإنترنت',
        'other_expense' => 'مصروفات أخرى',
        'expenses_chart' => 'المصروفات',
        'drivers' => 'السائقين',
        'bulk_edit' => 'تعديل جماعي',
        'add_multiple' => 'إضافة سائقين متعددة',
        'select_all' => 'تحديد الكل',
        'id' => 'ID',
        'iqama' => 'رقم الإقامة',
        'name' => 'اسم السائق',
        'license' => 'رقم الرخصة',
        'type' => 'النوع',
        'salary' => 'الراتب',
        'vehicle' => 'المركبة',
        'actions' => 'إجراءات',
        'link_vehicle' => 'ربط مركبة بالسائق',
        'vehicle_form' => 'استمارة المركبة',
        'confirm' => 'تأكيد',
        'add_row' => 'إضافة صف',
        'save_all' => 'حفظ الكل',
        'save' => 'حفظ',
        'cancel' => 'إلغاء',
        'confirm_delete' => 'هل أنت متأكد؟',
        'warning_delete' => 'لن تستطيع التراجع!',
        'yes_delete' => 'نعم احذف',
        'toast_add_driver' => 'تم إضافة السائق بنجاح',
        'toast_update_driver' => 'تم تحديث بيانات السائق',
        'toast_link_vehicle' => 'تم ربط المركبة بالسائق',
        'toast_add_multiple' => 'تم إضافة السائقين بنجاح',
        'toast_bulk_update' => 'تم تحديث السائقين',
        'error_msg' => 'حصل خطأ',
        'confirm_delete' => 'هل أنت متأكد؟',
        'warning_delete' => 'لن تستطيع التراجع!',
        'yes_delete' => 'نعم احذف',
        'cancel' => 'إلغاء',
        'select_one_driver' => 'اختار سائق واحد على الأقل',
        'vehicles' => 'المركبات',
        'bulk_edit' => 'تعديل جماعي',
        'add_vehicles' => 'إضافة مركبات',
        'select_one_vehicle' => 'اختار مركبة واحدة على الأقل',
        'are_you_sure' => 'هل أنت متأكد؟',
        'warning_delete' => 'لن تستطيع التراجع!',
        'yes_delete' => 'نعم احذف',
        'cancel' => 'إلغاء',
        'update_done' => 'تم التحديث',
        'add_done' => 'تمت الإضافة',
        'id' => 'ID',
        'type' => 'نوع المركبة',
        'model' => 'موديل المركبة',
        'ownership' => 'الملكية',
        'plate' => 'رقم اللوحة',
        'image' => 'الاستمارة',
        'actions' => 'إجراءات',
        'vehicles' => 'المركبات',
        'bulk_edit_vehicles' => 'تعديل جماعي للمركبات',
        'add_vehicles' => 'إضافة مركبات',
        'select_one_vehicle' => 'اختار مركبة واحدة على الأقل',

        'confirm_delete' => 'هل أنت متأكد؟',
        'delete_warning' => 'لن تستطيع التراجع!',
        'yes_delete' => 'نعم احذف',
        'cancel' => 'إلغاء',

        'select_one_vehicle_alert' => 'اختار مركبة واحدة على الأقل',
        'update_success' => 'تم التحديث',
        'add_success' => 'تمت الإضافة',
        'company' => 'شركة',
        'rented' => 'مستأجرة',
        'expenses' => 'البنزين والصيانة',
        'bulk_edit_expenses' => 'تعديل جماعي للعمليات',
        'add_multiple_expenses' => 'إضافة عمليات متعددة',

        'driver' => 'السائق',
        'service_type' => 'نوع الخدمة',
        'amount' => 'المبلغ',
        'problem_description' => 'وصف العطل',
        'invoice' => 'الفاتورة',
        'date' => 'التاريخ',
        'date_time' => 'التاريخ والوقت',

        'fuel' => 'بنزين',
        'internet' => 'انترنت',
        'maintenance' => 'عطل وصيانة',
        'other' => 'أخرى',

        'delete_expense' => 'حذف العملية',

        'select_one_expense' => 'اختار عملية واحدة على الأقل',

        'add_row' => 'إضافة صف',

        'update_success' => 'تم التحديث',
        'add_success' => 'تمت الإضافة',
        'delete_operation' => 'حذف العملية',
        'select_one_expense' => 'اختار عملية واحدة على الأقل',
        'fuel' => 'بنزين',
        'internet' => 'انترنت',
        'maintenance' => 'عطل وصيانة',
        'other' => 'أخرى',
        'problem_description' => 'وصف العطل',
        'date_time' => 'التاريخ والوقت',
        'choose_vehicle' => 'اختر مركبة',
        'delete_vehicle' => 'حذف المركبة',
        'reports_drivers' => 'تقارير السائقين',
        'all_drivers' => 'كل السائقين',
        'export_excel' => 'تصدير Excel',
        'export_pdf' => 'تصدير PDF',

        'fuel' => 'بنزين',
        'maintenance' => 'صيانة',
        'internet' => 'انترنت',
        'other' => 'أخرى',

        'currency_sar' => 'ريال',

        'total' => 'الإجمالي',

        'driver' => 'السائق',
        'month' => 'الشهر',

        'filter_month' => 'اختر الشهر',
        'filter_driver' => 'اختر السائق',
        'drivers_report' => 'تقرير السائقين',
        'drivers_data' => 'بيانات السائقين',

        'iqama' => 'الإقامة',
        'code' => 'الكود',
        'mobile' => 'الجوال',
        'details' => 'التفاصيل',

        'days' => 'الأيام',

        'fuel' => 'بنزين',
        'maintenance' => 'صيانة',
        'internet' => 'انترنت',
        'other' => 'أخرى',

        'total' => 'الإجمالي',
        'total_all_services' => 'إجمالي كل الخدمات',
        'drivers_data' => 'بيانات السائقين',
        'name' => 'الاسم',
        'iqama' => 'رقم الإقامة',
        'code' => 'الكود',
        'mobile' => 'الجوال',
        'days' => 'الأيام',
        'detail' => 'تفاصيل',
        'gasoline' => 'بنزين',
        'maintenance' => 'صيانة',
        'internet' => 'انترنت',
        'other' => 'أخرى',
        'total' => 'الإجمالي',
        'grand_total' => 'الإجمالي الكلي',
        'drivers_report_file' => 'تقرير السائقين',
        'login_title' => 'تسجيل دخول الأدمن',
        'username' => 'اسم المستخدم',
        'password' => 'كلمة المرور',
        'login_btn' => 'تسجيل الدخول',
        'login_error' => 'اسم المستخدم أو كلمة المرور غير صحيحة',
        'admin_login' => 'تسجيل الدخول',
    ],

    'en' => [
        'dashboard' => 'Dashboard',
        'home' => 'Home',
        'drivers' => 'Drivers',
        'vehicles' => 'Vehicles',
        'expenses' => 'Fuel & Maintenance',
        'reports' => 'Reports',
        'logout' => 'Logout',
        'welcome' => 'Welcome',
        'confirm_logout' => 'Confirm Logout',
        'logout_msg' => 'Are you sure you want to logout?',
        'cancel' => 'Cancel',
        'yes_logout' => 'Yes, Logout',
        'dashboard_title' => 'Dashboard',
        'choose_month' => 'Select Month',
        'drivers_count' => 'Drivers Count',
        'vehicles_count' => 'Vehicles Count',
        'fuel_expense' => 'Fuel Expense',
        'maintenance_expense' => 'Maintenance Expense',
        'internet_expense' => 'Internet Expense',
        'other_expense' => 'Other Expenses',
        'expenses_chart' => 'Expenses',
        'drivers' => 'Drivers',
        'bulk_edit' => 'Bulk Edit',
        'add_multiple' => 'Add Multiple Drivers',
        'select_all' => 'Select All',
        'id' => 'ID',
        'iqama' => 'Iqama Number',
        'name' => 'Driver Name',
        'license' => 'License Number',
        'type' => 'Type',
        'salary' => 'Salary',
        'vehicle' => 'Vehicle',
        'actions' => 'Actions',
        'link_vehicle' => 'Link Vehicle',
        'vehicle_form' => 'Vehicle Form',
        'confirm' => 'Confirm',
        'add_row' => 'Add Row',
        'save_all' => 'Save All',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'confirm_delete' => 'Are you sure?',
        'warning_delete' => 'You cannot undo this!',
        'yes_delete' => 'Yes Delete',
        'toast_add_driver' => 'Driver added successfully',
        'toast_update_driver' => 'Driver updated successfully',
        'toast_link_vehicle' => 'Vehicle linked successfully',
        'toast_add_multiple' => 'Drivers added successfully',
        'toast_bulk_update' => 'Drivers updated successfully',
        'error_msg' => 'Something went wrong',
        'confirm_delete' => 'Are you sure?',
        'warning_delete' => 'You cannot undo this!',
        'yes_delete' => 'Yes Delete',
        'cancel' => 'Cancel',
        'select_one_driver' => 'Select at least one driver',
        'vehicles' => 'Vehicles',
        'bulk_edit' => 'Bulk Edit',
        'add_vehicles' => 'Add Vehicles',
        'select_one_vehicle' => 'Select at least one vehicle',
        'are_you_sure' => 'Are you sure?',
        'warning_delete' => 'You cannot undo this!',
        'yes_delete' => 'Yes, delete',
        'cancel' => 'Cancel',
        'update_done' => 'Updated successfully',
        'add_done' => 'Added successfully',
        'id' => 'ID',
        'type' => 'Type',
        'model' => 'Model',
        'ownership' => 'Ownership',
        'plate' => 'Plate Number',
        'image' => 'Registration',
        'actions' => 'Actions',
        'vehicles' => 'Vehicles',
        'bulk_edit_vehicles' => 'Bulk Edit Vehicles',
        'add_vehicles' => 'Add Vehicles',
        'select_one_vehicle' => 'Select at least one vehicle',

        'confirm_delete' => 'Are you sure?',
        'delete_warning' => 'You cannot undo this!',
        'yes_delete' => 'Yes Delete',
        'cancel' => 'Cancel',

        'select_one_vehicle_alert' => 'Select at least one vehicle',
        'update_success' => 'Updated successfully',
        'add_success' => 'Added successfully',
        'company' => 'Company',
        'rented' => 'Rented',
        'expenses' => 'Fuel & Maintenance',
        'bulk_edit_expenses' => 'Bulk Edit Expenses',
        'add_multiple_expenses' => 'Add Multiple Expenses',

        'driver' => 'Driver',
        'service_type' => 'Service Type',
        'amount' => 'Amount',
        'problem_description' => 'Problem Description',
        'invoice' => 'Invoice',
        'date' => 'Date',
        'date_time' => 'Date & Time',

        'fuel' => 'Fuel',
        'internet' => 'Internet',
        'maintenance' => 'Maintenance',
        'other' => 'Other',

        'delete_expense' => 'Delete Expense',

        'select_one_expense' => 'Select at least one expense',

        'add_row' => 'Add Row',

        'update_success' => 'Updated successfully',
        'add_success' => 'Added successfully',
        'delete_operation' => 'Delete Operation',
        'select_one_expense' => 'Select at least one expense',
        'fuel' => 'Fuel',
        'internet' => 'Internet',
        'maintenance' => 'Maintenance',
        'other' => 'Other',
        'problem_description' => 'Problem Description',
        'date_time' => 'Date & Time',
        'choose_vehicle' => 'Choose Vehicle',
        'delete_vehicle' => 'Delete Vehicle',
        'reports_drivers' => 'Driver Reports',
        'all_drivers' => 'All Drivers',
        'export_excel' => 'Export Excel',
        'export_pdf' => 'Export PDF',

        'fuel' => 'Fuel',
        'maintenance' => 'Maintenance',
        'internet' => 'Internet',
        'other' => 'Other',

        'currency_sar' => 'SAR',

        'total' => 'Total',

        'driver' => 'Driver',
        'month' => 'Month',

        'filter_month' => 'Select Month',
        'filter_driver' => 'Select Driver',
        'drivers_report' => 'Drivers Report',
        'drivers_data' => 'Drivers Data',

        'iqama' => 'Iqama',
        'code' => 'Code',
        'mobile' => 'Mobile',
        'details' => 'Details',

        'days' => 'Days',

        'fuel' => 'Fuel',
        'maintenance' => 'Maintenance',
        'internet' => 'Internet',
        'other' => 'Other',

        'total' => 'Total',
        'total_all_services' => 'Total All Services',
        'drivers_data' => 'Drivers Data',
        'name' => 'Name',
        'iqama' => 'Iqama',
        'code' => 'Code',
        'mobile' => 'Mobile',
        'days' => 'Days',
        'detail' => 'Detail',
        'gasoline' => 'Gasoline',
        'maintenance' => 'Maintenance',
        'internet' => 'Internet',
        'other' => 'Other',
        'total' => 'Total',
        'grand_total' => 'Grand Total',
        'drivers_report_file' => 'Drivers Report',
        'login_title' => 'Admin Login',
        'username' => 'Username',
        'password' => 'Password',
        'login_btn' => 'Login',
        'login_error' => 'Invalid username or password',
        'admin_login' => 'Login',
    ]
];